### ISSUE TITLE
Two digit years are saved as 00XX

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/road_closings#112]
If you enter 15 for a year, it is saved as 0015 or 15AD.  We need to somehow handle 2 digit years better.

**Comment by inghamn** [comment]
We might consider starting to use a date picker.  I've used them in previous applications with some users complaining about them, and some users liking them.

There's also a concern about accessibility.  I've still yet to come across a datepicker that any accessibility person likes.  Keyboard control and screen reader support are non-obvious.

Still, I saw:
https://github.com/bevacqua/rome

**Comment by charlesbrandt** [comment]
What about the date input type?

```
<input type="date" name="bday">
```

That way browsers that support it will render a date picker automatically.

**Comment by inghamn** [comment]
The only browser that does this, so far, is Chrome.

**Comment by inghamn** [comment]
Although, there is finally a developer working on it for Firefox
https://bugzilla.mozilla.org/show_bug.cgi?id=825294

And IE Edge is working on it
https://dev.windows.com/en-us/microsoft-edge/platform/status/timerelatedinputtypes

Do we just do input type="date" and let browsers start handling the picker whenever they finally get around to it?

**Comment by charlesbrandt** [comment]
I think we should do that, at a minimum. If there is a way to add support via javascript for older browsers, then I'm open to doing that in addition to the new date input type.

**Comment by inghamn** [comment]
The problem we had before was the javascript date picker would show up....and...with browsers that supported input type="date' the browser's date picker would also show up.  Both would be stacked on top of each other.

**Comment by inghamn** [comment]
Added a validation check

2db554363426e4f9d112ea0ea4440e11ce79072d

**Comment by inghamn** [comment]
All browsers now implement a date picker for HTML 5 date inputs
