### ISSUE TITLE
Extend the range of events included in weekly emails

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/road_closings#118]
"inRoads group emails only include closing for the upcoming week sent on the friday prior. The app includes closings 30 days out or more. It would be nice to include those closings as well so I don't have to check the app unless i need more details."

via: https://bloomington.in.gov/crm/tickets/view?ticket_id=150526

**Comment by inghamn** [comment]
What app are we talking about?

**Comment by charlesbrandt** [comment]
The app refers to the [web based application, inRoads](https://bloomington.in.gov/inroads/events)

**Comment by inghamn** [comment]
Would it make sense to include all future road closings that have been entered so far?

**Comment by charlesbrandt** [comment]
That could be good, but I think we'll want to create two sections in the email:

  - Events active this week (current version)
  - Other events active after this week (could be all future closings)

I'd want to avoid overlap/duplicates from one section to the other.

**Comment by rbdietz** [comment]
Might consider breaking it up by...
1: active this coming week
2: active after this coming week
