### ISSUE TITLE
Upgrade to latest Google API

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/road_closings#129]
Google is now on version 4 of their PHP library for making API calls.  We should try and keep up with them.

**Comment by inghamn** [comment]
This is required for switching to composer. #141

**Comment by rbdietz** [comment]
Make sure this doesn't hose other applications shifting to v4

**Comment by inghamn** [comment]
The PHP library v2 is the latest version.  Since we're using composer, we'll always get the latest version when we compile a release.
