### ISSUE TITLE
Drop noise permits from inRoads

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/road_closings#130]
Historically, noise permits were in the public works calendar just so employees had all their permitting in one place.  Noise permits do not result in a street closure by themselves; in fact, it was double entry in inRoads, as the street closures for events with noise permits were also entered into inRoads.

The police department already gets a copy of noise permits by other means, and does not need them published here.

**Comment by rbdietz** [comment]
Noise permits should stay in inRoads until there is another
application/process to post noise permits to the public.  It's not a
problem to have informing in inRoads that doesn't close a road.
