### ISSUE TITLE
Create activity log

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/road_closings#138]
We want to be able to know who made what changes to the system.  We should start by tracking changes to the road closing events. 

We usually do this with a seperate log table, and including a json dump of the data before and after the change.

**Comment by inghamn** [comment]
This is going to be a lot more involved than originally thought.

We need to redesign the HTML & CSS to accommodate displaying this information somewhere.

We probably want to log a deletion as a change - which means not actually deleting anything.  Rather, we'd want to only flag it as deleted, so we can have a place to link from to show the history for the deleted item.

**Comment by inghamn** [comment]
This will capture the data entry person as described in #143

**Comment by rbdietz** [comment]
This doesn't need to be fancy, it can just jump to a popup window.
