### ISSUE TITLE
Primary point of contact field

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/road_closings#143]
Planning & Transportation has requested a new field for the primary point of contact. This should only be visible to logged in users. This would be for reference about who did the data entry. This is helpful when there are questions from other staff or the public.

**Comment by inghamn** [comment]
Should it be the person doing the data entry? Or should the data entry person choose who the contact person is?  This is similar to Master Address; the data entry is not necessarily done by who's responsible for the event.

**Comment by inghamn** [comment]
In the meeting we said we wanted to capture the person doing the data entry as well as selecting a (possibly) different person as the point of contact.   The point of contact is not often the person who's doing the entry in the web application.

**Comment by inghamn** [comment]
The person chooser requires #155

**Comment by inghamn** [comment]
Do we event want to be adding the point of contact as a "Person" in the system?  Should it, instead, just be another plain text field that employees can type whatever they feel they need to about contact information?

**Comment by charlesbrandt** [comment]
I think it's fine if this is a plain text field.

**Comment by inghamn** [comment]
I'm all confused now.  I think there's three things going on.

* who did the data entry
* what contact info we show to the public
* internal primary contact info

These three things can all be different people.  Do we want to split out the publicly displayed contact info into a seperate field as well?  Right now, employees mix that information into the event description.

An example:
For a public works closing:
* the public contact info would be the contactor's information
* the primary contact would be head of public works
* the data entry was done by some staff member of public works.

**Comment by charlesbrandt** [comment]
I think it's fine to keep publicly displayed contact information as part of the event description. If internal users want that as a separate field, I would rather add that later. So for now: 

  - who did the data entry
  - internal primary contact info
