### ISSUE TITLE
Allow notifications for new closures / events

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/road_closings#144]
When new events are added to the system, a subset of users would like to receive a notification email about the new events. 

This feature should allow configuration of the group of users, along with sending the notification when new events are added to the system. 

Initially, Andrew, Adam and Terri have all requested to receive these alerts.

**Comment by inghamn** [comment]
inRoads will need a way to identify users who want these notifications.  Users should probably be able to sign themselves up, which implies some sort of "My Account" edit screen, which we'll need to build.

**Comment by rbdietz** [comment]
Or they subscribe to a google group for this purpose

**Comment by inghamn** [comment]
We're looking at this type of notification, as well as #151.  Plus I suspect we'll have even more types of notifications to send out.  It doesn't seem like we want to keep creating more and more google groups (one for each type of notification).

It seems like inRoads should send emails directly to individual users.

**Comment by inghamn** [comment]
I need to make notifications something that can be turned on and off.  I don't want to be sending out emails for every test event we do in test and staging.

Because of this and #151 we probably need an interface for maintaining the notifications and email lists.
