### ISSUE TITLE
Add a link to the individual event view

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/road_closings#154]
Clicking on an event on the home screen only expands/collapses the "teaser" event display.  We have a URL for displaying the full information for an event, but we never link to it from anywhere.

This is also causing problems with delete.  The full event view is the only place the delete button shows up, but you can't get there as we never draw a link to it.

We should add a link on the "teaser" list of events to the full view for each event.

**Comment by inghamn** [comment]
To do this, I think we'll need to get rid of linking to the entire event div to the expand/collapse function.

**Comment by inghamn** [comment]
Any recommendations for the wording on the link?  So far, I've just put in the text: "view".
![screen](https://user-images.githubusercontent.com/630282/41620497-dec6131c-73d7-11e8-9d24-23adb6f4387d.png)

**Comment by charlesbrandt** [comment]
I'd suggest:
  - Details
  - View details
  - Event details
  - More info (although maybe that's incorrect since there is not 'more info' to see)
