### ISSUE TITLE
CSS/JS versioning for cache busting

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/road_closings#183]
We keep having a problem with new releases.  Users report stuff not working right, which is fixed by clearing the cache and/or super-reloading (Shift - CTRL - R)

We should incorporate some sort of version or build numbering into CSS compiling (and probably JS, too).  Although, right now, we're not compiling JS, yet.

We're now diligently using semantic version numbers for issue tracking and releases.  We could start by using that as the version number (as opposed to something increment every build).

**Comment by charlesbrandt** [comment]
I'm also ok if the client side build scripts or bundler (e.g. gulp, webpack, etc) handle this in an automated way. Generally the built versions would not need to be kept under version control anyway.

**Comment by inghamn** [comment]
This shouldn't be client-side.  We don't want citizens to wait while their browser compiles stuff before showing anything on the page.  The build / compile stuff should all be done by a developer prior to putting it online.

**Comment by charlesbrandt** [comment]
That is what I meant -- build scripts for assets on the client side, not that the build would happen on the client side.

**Comment by inghamn** [comment]
We should implement it the way we did in Directory:
https://github.com/City-of-Bloomington/directory/commit/ea7af3a42c7cda8ff115cc8040080e3a81d7d580
