### ISSUE TITLE
Basemap no longer working

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/road_closings#199]
It looks like the Mapbox tile layer we were using is no longer available.  I don't know if it's account related, or if we just need to choose a new basemap tile layer.

**Comment by laurahaley** [comment]
I read that there is a new version of mapbox streets (v8) which will
require both updates to the source url and styling. However, version 7 is
supposed to be available until early next year so that might not be it.

**Comment by inghamn** [comment]
I'm guessing this is what's going on.  InRoads is still using v4.  I'll need to work on updating the mapbox code to v8

**Comment by laurahaley** [comment]
They might be on version 11 now.
https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/
https://docs.mapbox.com/help/troubleshooting/streets-v8-migration-guide/

**Comment by inghamn** [comment]
The configuration is only part of the solution, but it should at least make the site usable again.  The tiles are going to be blurry until we update our javascript to the latest version of the api.
