### ISSUE TITLE
Google User account for interaction

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/road_closings#20]
So, I have been glossing over this, but it came to a head when I tried to implement posting to the Google Group.

Use the Google Web Service API's requires all interaction be done on behalf of a valid Google User account.  So far, I've been using my own Google account to test things out.  But we may want to create a special account or something for this application.

I ran into this when I tried to limit posting to Managers or Owners of the google group.  However, once again, only valid Google accounts can be a manager or owner of the google group.

**Comment by inghamn** [comment]
Still an open issue, however I was able to override the group policy, and allow posting for specific email addresses.

**Comment by charlesbrandt** [comment]
We do have a dedicated account that we could use for this purpose now.

**Comment by inghamn** [comment]
This is now set in site_config.inc
