### ISSUE TITLE
Add JSON and XML output

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/road_closings#21]
We also want the search results available as a JSON and XML feed.  It doesn't need to be Open511, just generic for now.

We probably still want to do Open511 in the future.

**Comment by charlesbrandt** [comment]
Here are the links that google calendar provides:

XML
https://www.google.com/calendar/feeds/bloomington.in.gov_rm22gcl2hatcmjk0boh75d6pec%40group.calendar.google.com/public/basic

ICAL
https://www.google.com/calendar/ical/bloomington.in.gov_rm22gcl2hatcmjk0boh75d6pec%40group.calendar.google.com/public/basic.ics

HTML
https://www.google.com/calendar/embed?src=bloomington.in.gov_rm22gcl2hatcmjk0boh75d6pec%40group.calendar.google.com&ctz=America/New_York
