### ISSUE TITLE
Now, Today, Tomorrow adjustments

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/road_closings#22]
The ranges "Today" and "Tomorrow" should be set to midnight to midnight for the corresponding day.
"Now" should also be an option that only includes currently active events. 

The default should be set to "Today"

**Comment by inghamn** [comment]
The default parameters should be set to "Now".   "Now" should represent a small time slice, maybe start and end times within 5 minutes of each other.

All the rest of the date selections should be done with the rule:
startDates use time== 00:00
endDates use time = 23:59

**Comment by charlesbrandt** [comment]
Will "Now" typically have data to display? I'm concerned that if "Now" happens to not have any active closures (late at night, etc), users may think the system doesn't provide any valid information.

**Comment by inghamn** [comment]
I've dropped the "Now" we only have Today, Tomorrow, 7 days, and 30 days.  Today is the default.
