### ISSUE TITLE
Add city boundaries

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/road_closings#26]
We are hosting a city boundary as a layer in GeoServer.  We should try and import that layer using WMS.

**Comment by charlesbrandt** [comment]
Below is the url for the city's municipal boundary layer on geoserver in open layers format.  Go to https://geoserver.bloomington.in.gov to preview others using the layer preview option.

https://geoserver.bloomington.in.gov/geoserver/publicgis/wms?service=WMS&version=1.1.0&request=GetMap&layers=publicgis:BloomingtonMunicipalBoundary&styles=&bbox=3078000.0,1392000.0,3162000.0,1470000.0&width=512&height=475&srs=EPSG:2966&format=application/openlayers
