### ISSUE TITLE
Highlighted color for map drawings is red for all types

### ISSUE THREAD

**Issue by hiesterd** [City-of-Bloomington/road_closings#43]
When hovering over a lane closing, the drawing of the closing on the map turns red, instead of opaque.

**Comment by hiesterd** [comment]
This may simply be a configuration oversight. I'll take a look into it and report what I find.

**Comment by hiesterd** [comment]
Looks like it's not a configuration issue. @inghamn, can you look into this, and let me know what you find?

The desired highlight style for map lines is for their width to be increased by two pixels, and for the Alpha value of the corresponding RGBA color to go up to 1, and then back down to .6.

**Comment by inghamn** [comment]
We swap the entire style out on hover, and color is part of the style.  So, there's only a single hover style, and thus, only a single color used when hovering.

I'm not sure if we can dynamically alter the style of a feature.  So, far, I've only been able to swap the entire style on a feature.

**Comment by hiesterd** [comment]
What if we define entire styles for these different states in the config? E.g.

``` php
    [
        'code'        => 'laneRestriction',
        'name'        => 'Lane Restriction',
        'description' => 'expect short delays, signage in place.',
        'default'     => true,
        'rgba'        => [235, 150, 2, .6],
        'rgbaSolid'        => [235, 150, 2, 1],
    ],
```
