### ISSUE TITLE
Vertically center breadcrumbs / title in top nav

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/road_closings#47]
The breadcrumb / title section appears lower than the rest of the items in the top nav.

**Comment by hiesterd** [comment]
@charlesbrandt If you compare what's on the development server with what's on production right now, do you think the changes on the development server are enough to close this issue?

**Comment by charlesbrandt** [comment]
Yes, much better. I like that it doesn't dip down as low with the version on dev. Thanks Dan!
