### ISSUE TITLE
Way to delete an event

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/road_closings#50]
Is it possible to delete an event with the inRoads interface, or is this only available via the Google calendar itself?

**Comment by inghamn** [comment]
Correct, we have not, yet built a delete function in the inRoads application.   We may want to leave the delete functionality only in Google Calendar.  It will prevent abuse of the delete.

**Comment by inghamn** [comment]
Once we're using the local copy as the master, we'll have even more of a need to support deleting events.  We'll need to delete it from the local copy as well as the Google copy.

We won't be able to rely on just deleting it from the Google Calendar.
