### ISSUE TITLE
Add CSV as open data output format

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/road_closings#60]

**Comment by inghamn** [comment]
Is CSV really useful in this case?  We have fields that are large blocks of free-form text.  We'd need to use some other delimiter, such as '|', as well as clean out line breaks.  Anyone attempting to bring this into Excel would have a bit of manipulation to do.

XML and JSON make more sense, I think.  We can control the encapsulation for each field better.

**Comment by rbdietz** [comment]
CSV is more useful in the sense that more people could actually make use of it.

**Comment by hiesterd** [comment]
I'm not an engineer, so it may not be my place to ask, but I'm curious to know: What kinds of use cases are common for CSV files? I'm mostly familiar with people downloading them to their hard drive and opening them with Excel.

**Comment by rbdietz** [comment]
Thee point here is to make data available in formats that any interested
person can use.  Most visitors to the inRoads site aren't going to be able
to us the other formats without training or tools that they don't have.
They could actually do something with CSV even if it's not the best format
for a coder.

On Wed, Jul 15, 2015 at 2:37 PM, Dan Hiester notifications@github.com
wrote:

> I'm not an engineer, so it may not be my place to ask, but I'm curious to
> know: What kinds of use cases are common for CSV files? I'm mostly familiar
> with people downloading them to their hard drive and opening them with
> Excel.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/City-of-Bloomington/inRoads/issues/60#issuecomment-121707509
> .

## 

```
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov
```

**Comment by rbdietz** [comment]
CSV needs to remove commas from descriptions and other fields so it works.  Test output to make sure it works before closing issue.

**Comment by inghamn** [comment]
Is this still not working for you?  The CSV files I download are quoted and escaped so that it loads correctly for me.

**Comment by rbdietz** [comment]
There appears to be a hard return at line 6 and 7 that doesn't make sense.

**Comment by inghamn** [comment]
Tested it in MS Excel.  The file loads correctly in MS Excel, even with fields that have line breaks in them.

Yes, there are fields that have line breaks in them.  However, the fields are double quoted correctly.  On load, MS Excel's default import of a CSV uses comma as the field separator, and double quote as the text delimiter.
