### ISSUE TITLE
Show description of application somewhere

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/road_closings#63]
Maybe the footer could have a link to "About" that pops up a modal dialog with the following description:

Greater Bloomington road, sidewalk and parking status information including closings, lane reductions and reservations

The popup could also include other information from the footer, if that would help.

**Comment by rbdietz** [comment]
Could be in side panel above "Feedback".

**Comment by charlesbrandt** [comment]
We have a dedicated page for information about inRoads:

https://bloomington.in.gov/about-inroads

There is room for a button or link next to the "Feedback" button that could say "More Info" or "About"

**Comment by rbdietz** [comment]
Is this page connected into ITS is any way?
