### ISSUE TITLE
Waze format data export

### ISSUE THREAD

**Issue by rbdietz** [City-of-Bloomington/road_closings#71]
Configure output to export into Waze format.

**Comment by inghamn** [comment]
The waze feed format is documented here:
http://blog.waze.com/p/connected-citizens-partner-feeds-specs.html

**Comment by rbdietz** [comment]
Regex isn't a good long-term solution but if it works then we are good for the time being.

**Comment by hiesterd** [comment]
My guess is, a better long-term solution would be to change the drawing interface such that the drawings inherently create the data needed by Waze—it's a duplicate of data entry to have both a _hand-written copy_ of the roads scheduled for closure, and a _drawing_ of the roads scheduled for closure.
