### ISSUE TITLE
Waze feed should include current and future events

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/road_closings#82]
Right now the Waze feed will only include current events. Future events can be specified as parameters on the url, but this requires changing dates. We would like a static url that includes all current _and_ future events. e.g. format=waze-all

**Comment by inghamn** [comment]
We'll need to limit it to a date range.  All is infinite, as there are recurring events going out indefinitely.  I think I saw in the email that they can only take in stuff 5 days into the future.  Does that sounds right?

**Comment by rbdietz** [comment]
I think we could limit it to a month.  Feed users can ignore anything that
they don't want to use.

On Wed, Oct 7, 2015 at 11:52 AM, Cliff Ingham notifications@github.com
wrote:

> We'll need to limit it to a date range. All is infinite, as there are
> recurring events going out indefinitely. I think I saw in the email that
> they can only take in stuff 5 days into the future. Does that sounds right?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/City-of-Bloomington/inRoads/issues/82#issuecomment-146241688
> .

## 

```
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov
```

**Comment by inghamn** [comment]
The url is:

https:/bloomington.in.gov/inroads/waze

**Comment by rbdietz** [comment]
We should create a separate feed for trafficcast too.

On Wed, Oct 7, 2015 at 4:40 PM, Cliff Ingham notifications@github.com
wrote:

> The url is:
> 
> https:/bloomington.in.gov/inroads/waze
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/City-of-Bloomington/inRoads/issues/82#issuecomment-146321238
> .

## 

```
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov
```

**Comment by inghamn** [comment]
Do we know what format TrafficCast wants?  I was not able to find that information on their site.

**Comment by charlesbrandt** [comment]
Until we hear what changes they require, I would make it the same format as Waze. It would just be nice to have a separate route to allow these customizations to happen. See:
https://github.com/City-of-Bloomington/inRoads/issues/83

**Comment by rbdietz** [comment]
Let me know when the waze and trafficcast feeds are separated and and send
me the urls.  Thanks. -R

On Thu, Oct 8, 2015 at 10:17 AM, Charles Brandt notifications@github.com
wrote:

> Until we hear what changes they require, I would make it the same format
> as Waze. It would just be nice to have a separate route to allow these
> customizations to happen. See:
> #83 https://github.com/City-of-Bloomington/inRoads/issues/83
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/City-of-Bloomington/inRoads/issues/82#issuecomment-146560049
> .

## 

```
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov
```

**Comment by inghamn** [comment]
Okay, there are routes for Waze and TrafficCast
https://bloomington.in.gov/inroads/waze
https://bloomington.in.gov/inroads/trafficcast

**Comment by inghamn** [comment]
I thought we were expressly not doing the parameter form of the URL as that was not desired from Waze and TrafficCast.

**Comment by rbdietz** [comment]
I did not catch that from them.  If that's the case then no worries.

On Thu, Oct 8, 2015 at 10:51 AM, Cliff Ingham notifications@github.com
wrote:

> I thought we were expressly not doing the parameter form of the URL as
> that was not desired from Waze and TrafficCast.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/City-of-Bloomington/inRoads/issues/82#issuecomment-146569489
> .

## 

```
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov
```

**Comment by rbdietz** [comment]
They can't have a URL that changes; it need to be constant.  That doesn't
have anything to do with have parameters.  "?format=waze" is fine as long
at that URL provides the correct information no matter when it is accessed.

On Thu, Oct 8, 2015 at 10:51 AM, Cliff Ingham notifications@github.com
wrote:

> I thought we were expressly not doing the parameter form of the URL as
> that was not desired from Waze and TrafficCast.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/City-of-Bloomington/inRoads/issues/82#issuecomment-146569489
> .

## 

```
Rick Dietz, Director
Information & Technology Services Dept.
City of Bloomington, Indiana
812.349.3485 (office) 812.340.7958 (cell)
dietzr@bloomington.in.gov
```
