### ISSUE TITLE
New feed for TrafficCast

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/road_closings#83]
For now this feed can use the same output as Waze, but it would be nice to have a separate feed URL that we can tailor for their requirements, if needed. It should default to supplying all current and future events.

**Comment by inghamn** [comment]
We'll need to limit it to a date range, as all future events go on indefinitely.

**Comment by rbdietz** [comment]
Let's get this set up at...
http://bloomington.in.gov/inroads/events?format=trafficcast

**Comment by rbdietz** [comment]
Please get this url up so I can reconnect with trafficcast.

**Comment by inghamn** [comment]
The /waze and /trafficcast urls are still there for now.  If you use /waze or /trafficcast, you don't get to filter with additional parameters.  If you use the /events?format=waze form, you can provide all the additional parameters the site supports.

Waze (and TrafficCast) are set to show 30 days of events, by default.
