### ISSUE TITLE
delete icon is the same as cancel icon

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/road_closings#96]
When viewing a singular event, clicking the "X" will delete it (without warning).
When editing an event, clicking the "X" will cancel edits

This seems like it could be confusing.

**Comment by hiesterd** [comment]
There are a couple of things I've talked about with Cliff, to resolve this.
1. None of the clickable icons have `title` attributes. We need to add this functionality into the button helpers.
2. Interaction cancellation often doesn't work the same way in an user's mind as it does in a development team's mind. Most users click a link to start a workflow, realize they've clicked the wrong thing, and want to just simply "go back," or "go anywhere else." The word, "cancel," often doesn't enter their mind. As such, it may make sense for the cancel button in this application to be changed to a "Back Arrow" icon, to the left of the tabs.

**Comment by charlesbrandt** [comment]
I like the sound of a back arrow instead of the "X" for "go back"
